// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uspmlzuhzlbwubdrzooy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzcG1senVoemxid3ViZHJ6b295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTEzNjQsImV4cCI6MjA2NTgyNzM2NH0.AgRFMQmbSSpttJr9Taf7K4tsZTV8Uqx5QLkz5vvUXkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);